# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='likes',
        ),
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(to='social_app.Like'),
        ),
    ]
