# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='flags',
            new_name='links',
        ),
    ]
