# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='years_of_exp',
            new_name='years_of_experience',
        ),
    ]
