# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_auto_20160307_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='links',
        ),
        migrations.DeleteModel(
            name='LinkTo',
        ),
        migrations.AddField(
            model_name='topic',
            name='teams',
            field=models.ManyToManyField(to='social_app.Team'),
        ),
    ]
