# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20160307_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(choices=[('Bills', 'Buffalo Bills'), ('Dolphins', 'Miami Dolphins'), ('Patriots', 'New England Patriots'), ('Jets', 'New York Jets'), ('Ravens', 'Baltimore Ravens'), ('Bengals', 'Cincinnati Bengals'), ('Browns', 'Cleveland Browns'), ('Steelers', 'Pittsburgh Steelers'), ('Texans', 'Houston Texans'), ('Colts', 'Indianapolis Colts'), ('Jaguars', 'Jacksonville Jaguars'), ('Titans', 'Tennessee Titans'), ('Broncos', 'Denver Broncos'), ('Chiefs', 'Kansas City Chiefs'), ('Raiders', 'Oakland Raiders'), ('Chargers', 'San Diego Chargers')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nfl_teams',
            field=models.ManyToManyField(to='social_app.Team'),
        ),
    ]
