# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20160307_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammate',
            name='topic',
        ),
    ]
