# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_remove_teammate_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-time_created']},
        ),
    ]
