# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_auto_20160308_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
