# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_auto_20160307_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nfl_teams',
        ),
        migrations.AddField(
            model_name='topic',
            name='nfl_teams',
            field=models.ManyToManyField(to='social_app.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
    ]
