# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_auto_20160307_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='nfl_teams',
            new_name='teams',
        ),
    ]
