# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_topic_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
