# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_auto_20160307_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='teammate',
            name='teammate',
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_teammate', to='social_app.Teammate'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_teammate', to='social_app.Teammate'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='social_app.Relationship', to='social_app.Teammate'),
        ),
    ]
