# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_auto_20160307_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')], default=1),
            preserve_default=False,
        ),
    ]
