# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_auto_20160308_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
