# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_auto_20160308_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-team_name']},
        ),
    ]
