# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_remove_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='like',
        ),
    ]
