# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_auto_20160308_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='message_post',
            field=models.CharField(max_length=50),
        ),
    ]
