# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_auto_20160308_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='message_post',
            new_name='title',
        ),
    ]
